apiVersion: apps/v1
kind: Deployment
metadata:
  name: image-service
  namespace: patientsystem
spec:
  replicas: 1
  selector:
    matchLabels:
      app: image-service
  template:
    metadata:
      labels:
        app: image-service
    spec:
      containers:
        - name: image-service
          image: image-service:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 3001
              name: http
          env:
            - name: NODE_ENV
              value: "production"
            - name: DB_HOST
              value: "mysql-service"
            - name: DB_PORT
              value: "3306"
            - name: DB_NAME
              value: "patientsystemdb"
            - name: DB_USER
              value: "root"
            - name: DB_PASSWORD
              value: "rootpassword"
            - name: UPLOAD_DIR
              value: "/app/uploads"
          volumeMounts:
            - name: image-uploads
              mountPath: /app/uploads  # HÃ¤r sparas alla uppladdade bilder
      volumes:
        - name: image-uploads
          persistentVolumeClaim:
            claimName: image-uploads-pvc