apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: image-uploads-pvc
  namespace: patientsystem
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi  # 10GB för bilder (ändra efter behov)