apiVersion: v1
kind: Service
metadata:
  name: clinical-service
  namespace: patientsystem
spec:
  selector:
    app: clinical-service
  ports:
  - protocol: TCP
    port: 8082
    targetPort: 8082
    nodePort: 30082
  type: NodePort
